export const COLLABORATION_PARTY_NAME = "main"
export const COLLABORATION_XML_FRAGMENT = "default"
export const COLLABORATION_FLUSH_PATH = "/flush"
export const COLLABORATION_PERSIST_DEBOUNCE_WAIT_MS = 1500
export const COLLABORATION_PERSIST_DEBOUNCE_MAX_WAIT_MS = 3000
