import { authkitProxy } from "@workos-inc/authkit-nextjs"

export default authkitProxy()

export const config = {
  matcher: [
    "/",
    "/login",
    "/signup",
    "/forgot-password",
    "/inbox",
    "/invites",
    "/assigned",
    "/chats",
    "/settings/:path*",
    "/onboarding",
    "/workspace/:path*",
    "/team/:path*",
    "/projects/:path*",
    "/items/:path*",
    "/docs/:path*",
    "/join/:path*",
    "/api/account/:path*",
    "/api/attachments/:path*",
    "/api/calls/:path*",
    "/api/invites/:path*",
    "/api/channel-posts/:path*",
    "/api/channels/:path*",
    "/api/chats/:path*",
    "/api/comments/:path*",
    "/api/documents/:path*",
    "/api/items/:path*",
    "/api/notifications/:path*",
    "/api/projects/:path*",
    "/api/profile/:path*",
    "/api/settings-images/:path*",
    "/api/teams/:path*",
    "/api/views/:path*",
    "/api/workspaces/:path*",
    "/api/workspace/:path*",
  ],
}
