import type { AppData } from "@/lib/domain/types"

export function createEmptyState(): AppData {
  return {
    currentUserId: "",
    currentWorkspaceId: "",
    workspaces: [],
    workspaceMemberships: [],
    teams: [],
    teamMemberships: [],
    users: [],
    labels: [],
    projects: [],
    milestones: [],
    workItems: [],
    workItemActivities: [],
    customPropertyDefinitions: [],
    customPropertyValues: [],
    documents: [],
    views: [],
    comments: [],
    attachments: [],
    notifications: [],
    invites: [],
    projectUpdates: [],
    conversations: [],
    calls: [],
    chatMessages: [],
    chatReadStates: [],
    channelPosts: [],
    channelPostComments: [],
    ui: {
      activeTeamId: "",
      activeInboxNotificationId: null,
      selectedViewByRoute: {},
      viewerViewConfigByRoute: {},
      viewerDirectoryConfigByRoute: {},
      viewerDirectoryPresetsByRoute: {},
      selectedDirectoryPresetByRoute: {},
      collaborationSidebarOpenBySurface: {},
      activeCreateDialog: null,
    },
  }
}
