import { addDays, subDays } from "date-fns"

import type {
  AppData,
  Call,
  ChannelPost,
  ChannelPostComment,
  ChatMessage,
  Comment,
  Conversation,
  Document,
  Invite,
  Label,
  Milestone,
  Notification,
  Project,
  ProjectUpdate,
  Team,
  TeamMembership,
  UserProfile,
  ViewDefinition,
  Workspace,
  WorkItem,
} from "@/lib/domain/types"
import {
  createDefaultTeamFeatureSettings,
  createDefaultTeamWorkflowSettings,
} from "@/lib/domain/types"
import { buildTeamWorkViews } from "@/lib/domain/default-views"

function iso(date: Date) {
  return date.toISOString()
}

function startHtml(title: string, body: string) {
  return `<h2>${title}</h2><p>${body}</p>`
}

export function createSeedState(): AppData {
  const now = new Date()
  const recipeWorkflow = createDefaultTeamWorkflowSettings()
  recipeWorkflow.statusOrder = [
    "todo",
    "backlog",
    "in-progress",
    "done",
    "cancelled",
    "duplicate",
  ]
  recipeWorkflow.templateDefaults["software-delivery"].targetWindowDays = 24
  recipeWorkflow.templateDefaults["software-delivery"].summaryHint =
    "Product delivery plan for customer-facing work, release quality, and shipped capabilities."
  recipeWorkflow.templateDefaults["bug-tracking"].targetWindowDays = 10

  const developmentWorkflow = createDefaultTeamWorkflowSettings()
  developmentWorkflow.statusOrder = [
    "backlog",
    "in-progress",
    "todo",
    "done",
    "cancelled",
    "duplicate",
  ]
  developmentWorkflow.templateDefaults["software-delivery"].defaultPriority =
    "urgent"
  developmentWorkflow.templateDefaults["software-delivery"].targetWindowDays =
    18
  developmentWorkflow.templateDefaults["project-management"].defaultViewLayout =
    "list"

  const operationsWorkflow =
    createDefaultTeamWorkflowSettings("project-management")
  operationsWorkflow.statusOrder = [
    "backlog",
    "todo",
    "in-progress",
    "done",
    "cancelled",
    "duplicate",
  ]
  operationsWorkflow.templateDefaults["project-management"].targetWindowDays =
    45
  operationsWorkflow.templateDefaults["project-management"].defaultViewLayout =
    "timeline"

  const workspace: Workspace = {
    id: "workspace_recipe_room",
    slug: "recipe-room",
    name: "Recipe Room",
    logoUrl: "RR",
    workosOrganizationId: null,
    settings: {
      accent: "emerald",
      description:
        "A Linear-style workspace that combines product delivery, issue tracking, and operational docs.",
    },
  }

  const teams: Team[] = [
    {
      id: "team_recipe_room",
      workspaceId: workspace.id,
      slug: "recipe-room",
      name: "Recipe Room",
      icon: "robot",
      settings: {
        joinCode: "RECIPE24",
        summary: "Customer-facing product work and issue triage.",
        guestProjectIds: ["project_release_hub"],
        guestDocumentIds: ["doc_release_playbook"],
        guestWorkItemIds: ["item_auth_reliability"],
        experience: "software-development",
        features: {
          ...createDefaultTeamFeatureSettings("software-development"),
          chat: true,
          channels: true,
        },
        workflow: recipeWorkflow,
      },
    },
    {
      id: "team_development",
      workspaceId: workspace.id,
      slug: "development",
      name: "Development",
      icon: "code",
      settings: {
        joinCode: "DEV42",
        summary: "Platform, architecture, and engineering health.",
        guestProjectIds: [],
        guestDocumentIds: [],
        guestWorkItemIds: [],
        experience: "software-development",
        features: {
          ...createDefaultTeamFeatureSettings("software-development"),
          chat: true,
        },
        workflow: developmentWorkflow,
      },
    },
    {
      id: "team_operations",
      workspaceId: workspace.id,
      slug: "project-management",
      name: "Project Management",
      icon: "kanban",
      settings: {
        joinCode: "OPSJOIN",
        summary:
          "Program planning, launch coordination, and delivery follow-through.",
        guestProjectIds: [],
        guestDocumentIds: [],
        guestWorkItemIds: [],
        experience: "project-management",
        features: {
          ...createDefaultTeamFeatureSettings("project-management"),
          docs: true,
          chat: true,
        },
        workflow: operationsWorkflow,
      },
    },
  ]

  const users: UserProfile[] = [
    {
      id: "user_declan",
      name: "Declan Cowen",
      handle: "declan",
      email: "declan@example.com",
      avatarUrl: "DC",
      workosUserId: null,
      title: "Founder / Product",
      preferences: {
        emailMentions: true,
        emailAssignments: true,
        emailDigest: true,
        theme: "light",
      },
    },
    {
      id: "user_maya",
      name: "Maya Chen",
      handle: "maya",
      email: "maya@example.com",
      avatarUrl: "MC",
      workosUserId: null,
      title: "Engineering Lead",
      preferences: {
        emailMentions: true,
        emailAssignments: true,
        emailDigest: false,
        theme: "light",
      },
    },
    {
      id: "user_sofia",
      name: "Sofia Patel",
      handle: "sofia",
      email: "sofia@example.com",
      avatarUrl: "SP",
      workosUserId: null,
      title: "Product Designer",
      preferences: {
        emailMentions: true,
        emailAssignments: false,
        emailDigest: true,
        theme: "light",
      },
    },
    {
      id: "user_idris",
      name: "Idris Cole",
      handle: "idris",
      email: "idris@example.com",
      avatarUrl: "IC",
      workosUserId: null,
      title: "QA Lead",
      preferences: {
        emailMentions: true,
        emailAssignments: true,
        emailDigest: false,
        theme: "light",
      },
    },
    {
      id: "user_theo",
      name: "Theo James",
      handle: "theo",
      email: "theo@example.com",
      avatarUrl: "TJ",
      workosUserId: null,
      title: "Operations Manager",
      preferences: {
        emailMentions: false,
        emailAssignments: true,
        emailDigest: true,
        theme: "light",
      },
    },
  ]

  const teamMemberships: TeamMembership[] = [
    { teamId: "team_recipe_room", userId: "user_declan", role: "admin" },
    { teamId: "team_recipe_room", userId: "user_maya", role: "member" },
    { teamId: "team_recipe_room", userId: "user_sofia", role: "member" },
    { teamId: "team_recipe_room", userId: "user_idris", role: "member" },
    { teamId: "team_recipe_room", userId: "user_theo", role: "guest" },
    { teamId: "team_development", userId: "user_declan", role: "member" },
    { teamId: "team_development", userId: "user_maya", role: "admin" },
    { teamId: "team_development", userId: "user_sofia", role: "viewer" },
    { teamId: "team_development", userId: "user_idris", role: "member" },
    { teamId: "team_operations", userId: "user_theo", role: "admin" },
    { teamId: "team_operations", userId: "user_declan", role: "member" },
  ]

  const labels: Label[] = [
    { id: "label_frontend", name: "Frontend", color: "blue" },
    { id: "label_mobile", name: "Mobile", color: "violet" },
    { id: "label_design", name: "Design", color: "amber" },
    { id: "label_release", name: "Release", color: "emerald" },
    { id: "label_qa", name: "QA", color: "rose" },
    { id: "label_docs", name: "Docs", color: "cyan" },
  ]

  const projects: Project[] = [
    {
      id: "project_web_refresh",
      scopeType: "team",
      scopeId: "team_recipe_room",
      templateType: "software-delivery",
      name: "Web Refresh",
      summary: "Modernize the web client shell and issue workflows.",
      description:
        "This project tracks the rollout of the desktop-class web shell, filters, views, and work item detail experiences.",
      leadId: "user_declan",
      memberIds: ["user_declan", "user_sofia", "user_maya"],
      health: "on-track",
      priority: "high",
      status: "active",
      startDate: iso(subDays(now, 10)),
      targetDate: iso(addDays(now, 25)),
      createdAt: iso(subDays(now, 24)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "project_mobile_app",
      scopeType: "team",
      scopeId: "team_recipe_room",
      templateType: "software-delivery",
      name: "Mobile & App",
      summary:
        "Bring the same experience to mobile shells and native wrappers.",
      description:
        "Shared product work spanning mobile behavior, deep linking, and release stability.",
      leadId: "user_maya",
      memberIds: ["user_declan", "user_maya", "user_idris"],
      health: "at-risk",
      priority: "medium",
      status: "active",
      startDate: iso(subDays(now, 14)),
      targetDate: iso(addDays(now, 32)),
      createdAt: iso(subDays(now, 27)),
      updatedAt: iso(subDays(now, 2)),
    },
    {
      id: "project_release_hub",
      scopeType: "workspace",
      scopeId: workspace.id,
      templateType: "project-management",
      name: "Release Hub",
      summary: "Cross-team launch and operating checklist.",
      description:
        "A workspace-level program for launch readiness, docs, and post-release follow-through.",
      leadId: "user_theo",
      memberIds: ["user_declan", "user_theo", "user_idris"],
      health: "no-update",
      priority: "medium",
      status: "planning",
      startDate: iso(subDays(now, 4)),
      targetDate: iso(addDays(now, 40)),
      createdAt: iso(subDays(now, 8)),
      updatedAt: iso(subDays(now, 3)),
    },
    {
      id: "project_auth_qa",
      scopeType: "team",
      scopeId: "team_recipe_room",
      templateType: "bug-tracking",
      name: "Auth & Access QA",
      summary:
        "Stability work for join flows, permission edges, and sign-in polish.",
      description:
        "Bug-tracking template focused on auth reliability, QA passes, and regression control.",
      leadId: "user_idris",
      memberIds: ["user_idris", "user_declan", "user_maya"],
      health: "on-track",
      priority: "high",
      status: "active",
      startDate: iso(subDays(now, 9)),
      targetDate: iso(addDays(now, 16)),
      createdAt: iso(subDays(now, 19)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "project_platform_docs",
      scopeType: "team",
      scopeId: "team_development",
      templateType: "software-delivery",
      name: "Platform Docs",
      summary: "Engineering documentation and operating notes.",
      description:
        "Internal documentation project used to test free-standing team docs and linked references.",
      leadId: "user_maya",
      memberIds: ["user_maya", "user_declan", "user_sofia"],
      health: "on-track",
      priority: "low",
      status: "active",
      startDate: iso(subDays(now, 20)),
      targetDate: iso(addDays(now, 55)),
      createdAt: iso(subDays(now, 35)),
      updatedAt: iso(subDays(now, 2)),
    },
  ]

  const milestones: Milestone[] = [
    {
      id: "milestone_beta",
      projectId: "project_web_refresh",
      name: "Interactive MVP",
      targetDate: iso(addDays(now, 10)),
      status: "in-progress",
    },
    {
      id: "milestone_auth",
      projectId: "project_auth_qa",
      name: "Permission audit",
      targetDate: iso(addDays(now, 6)),
      status: "todo",
    },
    {
      id: "milestone_launch",
      projectId: "project_release_hub",
      name: "Launch review",
      targetDate: iso(addDays(now, 26)),
      status: "backlog",
    },
  ]

  const descriptionDocs: Document[] = [
    {
      id: "doc_item_routes",
      kind: "item-description",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Routes description",
      content: startHtml(
        "Missing route page",
        "Design a resilient fallback route with clean empty-state messaging and desktop-aware navigation recovery."
      ),
      linkedProjectIds: ["project_web_refresh"],
      linkedWorkItemIds: ["item_routes_404"],
      createdBy: "user_declan",
      updatedBy: "user_sofia",
      createdAt: iso(subDays(now, 20)),
      updatedAt: iso(subDays(now, 3)),
    },
    {
      id: "doc_item_rls",
      kind: "item-description",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Review RLS description",
      content: startHtml(
        "Permissions audit",
        "Validate row-level security assumptions around invite acceptance, role changes, and cross-team doc visibility."
      ),
      linkedProjectIds: ["project_mobile_app", "project_auth_qa"],
      linkedWorkItemIds: ["item_review_rls"],
      createdBy: "user_maya",
      updatedBy: "user_maya",
      createdAt: iso(subDays(now, 12)),
      updatedAt: iso(subDays(now, 2)),
    },
    {
      id: "doc_item_auth",
      kind: "item-description",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Auth reliability description",
      content: startHtml(
        "Permission and invite reliability",
        "Guest and viewer access needs explicit audit coverage before the invite and join-code flows ship."
      ),
      linkedProjectIds: ["project_auth_qa", "project_release_hub"],
      linkedWorkItemIds: ["item_auth_reliability"],
      createdBy: "user_idris",
      updatedBy: "user_declan",
      createdAt: iso(subDays(now, 8)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "doc_item_mobile_cards",
      kind: "item-description",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Mobile cards description",
      content: startHtml(
        "Responsive cards",
        "Collapse metadata, keep drag affordances reachable, and preserve assignee/status visibility in tighter viewports."
      ),
      linkedProjectIds: ["project_mobile_app"],
      linkedWorkItemIds: ["item_mobile_cards"],
      createdBy: "user_sofia",
      updatedBy: "user_sofia",
      createdAt: iso(subDays(now, 17)),
      updatedAt: iso(subDays(now, 5)),
    },
    {
      id: "doc_item_release",
      kind: "item-description",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Release notes description",
      content: startHtml(
        "Release notes system",
        "Model release notes as linked docs so project updates and launch artifacts can share the same editor surface."
      ),
      linkedProjectIds: ["project_release_hub"],
      linkedWorkItemIds: ["item_release_notes"],
      createdBy: "user_declan",
      updatedBy: "user_theo",
      createdAt: iso(subDays(now, 11)),
      updatedAt: iso(subDays(now, 4)),
    },
  ]

  const teamDocs: Document[] = [
    {
      id: "doc_release_playbook",
      kind: "team-document",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Release Playbook",
      content:
        "<h1>Release Playbook</h1><p>Single place for launch sequencing, QA signoff, support handoff, and rollback notes.</p><ul><li>Confirm invite flows</li><li>Dry-run notification inbox</li><li>Validate desktop wrapper boot</li></ul>",
      linkedProjectIds: ["project_release_hub", "project_auth_qa"],
      linkedWorkItemIds: ["item_auth_reliability", "item_release_notes"],
      createdBy: "user_declan",
      updatedBy: "user_theo",
      createdAt: iso(subDays(now, 16)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "doc_shell_inventory",
      kind: "team-document",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Shell Inventory",
      content:
        "<h1>Shell Inventory</h1><p>Reference list of the sidebar, inbox, assigned work, views, filters, and item detail panels we need in the MVP.</p>",
      linkedProjectIds: ["project_web_refresh"],
      linkedWorkItemIds: ["item_routes_404"],
      createdBy: "user_sofia",
      updatedBy: "user_sofia",
      createdAt: iso(subDays(now, 14)),
      updatedAt: iso(subDays(now, 2)),
    },
    {
      id: "doc_platform_principles",
      kind: "team-document",
      workspaceId: workspace.id,
      teamId: "team_development",
      title: "Platform Principles",
      content:
        "<h1>Platform Principles</h1><p>Keep the renderer source-agnostic, keep realtime out of the UI contract, and treat Electron as a shell rather than a second app.</p>",
      linkedProjectIds: ["project_platform_docs"],
      linkedWorkItemIds: [],
      createdBy: "user_maya",
      updatedBy: "user_declan",
      createdAt: iso(subDays(now, 28)),
      updatedAt: iso(subDays(now, 6)),
    },
    {
      id: "doc_qa_matrix",
      kind: "team-document",
      workspaceId: workspace.id,
      teamId: "team_recipe_room",
      title: "Permission QA Matrix",
      content:
        "<h1>Permission QA Matrix</h1><p>Role coverage across workspace, team, project, work item, and document flows.</p><ul><li>Admin creates workspace</li><li>Member invites to team</li><li>Viewer read-only verification</li></ul>",
      linkedProjectIds: ["project_auth_qa"],
      linkedWorkItemIds: ["item_auth_reliability"],
      createdBy: "user_idris",
      updatedBy: "user_idris",
      createdAt: iso(subDays(now, 9)),
      updatedAt: iso(subDays(now, 2)),
    },
  ]

  const workspaceDocs: Document[] = [
    {
      id: "doc_workspace_operating_system",
      kind: "workspace-document",
      workspaceId: workspace.id,
      teamId: null,
      title: "Workspace Operating System",
      content:
        "<h1>Workspace Operating System</h1><p>Shared principles for how teams should structure projects, work, docs, and release coordination across the workspace.</p><ul><li>Use team docs for execution detail</li><li>Use workspace docs for shared standards</li><li>Keep private docs for rough thinking</li></ul>",
      linkedProjectIds: ["project_release_hub"],
      linkedWorkItemIds: [],
      createdBy: "user_declan",
      updatedBy: "user_declan",
      createdAt: iso(subDays(now, 13)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "doc_workspace_release_readiness",
      kind: "workspace-document",
      workspaceId: workspace.id,
      teamId: null,
      title: "Workspace Release Readiness",
      content:
        "<h1>Workspace Release Readiness</h1><p>Cross-team launch risks, ownership gaps, and rollout sequencing for the current milestone window.</p>",
      linkedProjectIds: ["project_release_hub", "project_platform_docs"],
      linkedWorkItemIds: [],
      createdBy: "user_maya",
      updatedBy: "user_sofia",
      createdAt: iso(subDays(now, 10)),
      updatedAt: iso(subDays(now, 2)),
    },
  ]

  const privateDocs: Document[] = [
    {
      id: "doc_private_notes_declan",
      kind: "private-document",
      workspaceId: workspace.id,
      teamId: null,
      title: "Founder Notes",
      content:
        "<h1>Founder Notes</h1><p>Scratchpad for product framing, rough interface calls, and things to test before they become shared docs.</p>",
      linkedProjectIds: [],
      linkedWorkItemIds: [],
      createdBy: "user_declan",
      updatedBy: "user_declan",
      createdAt: iso(subDays(now, 7)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "doc_private_research_declan",
      kind: "private-document",
      workspaceId: workspace.id,
      teamId: null,
      title: "Research Dump",
      content:
        "<h1>Research Dump</h1><p>Loose notes on navigation, document management, and collection affordances before we turn them into shared decisions.</p>",
      linkedProjectIds: [],
      linkedWorkItemIds: [],
      createdBy: "user_declan",
      updatedBy: "user_declan",
      createdAt: iso(subDays(now, 6)),
      updatedAt: iso(subDays(now, 0)),
    },
  ]

  const workItems: WorkItem[] = [
    {
      id: "item_routes_404",
      key: "REC-139",
      teamId: "team_recipe_room",
      type: "story",
      title: "Page for routes that don’t exist",
      descriptionDocId: "doc_item_routes",
      status: "backlog",
      priority: "high",
      assigneeId: "user_sofia",
      creatorId: "user_declan",
      parentId: null,
      primaryProjectId: "project_web_refresh",
      linkedProjectIds: ["project_release_hub"],
      linkedDocumentIds: ["doc_shell_inventory"],
      labelIds: ["label_frontend", "label_design"],
      milestoneId: "milestone_beta",
      startDate: iso(subDays(now, 2)),
      dueDate: iso(addDays(now, 3)),
      targetDate: iso(addDays(now, 5)),
      subscriberIds: ["user_declan", "user_sofia", "user_maya"],
      createdAt: iso(subDays(now, 19)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_review_rls",
      key: "REC-115",
      teamId: "team_recipe_room",
      type: "requirement",
      title: "Review RLS",
      descriptionDocId: "doc_item_rls",
      status: "todo",
      priority: "urgent",
      assigneeId: "user_declan",
      creatorId: "user_maya",
      parentId: null,
      primaryProjectId: "project_mobile_app",
      linkedProjectIds: ["project_auth_qa"],
      linkedDocumentIds: ["doc_qa_matrix"],
      labelIds: ["label_release", "label_qa"],
      milestoneId: "milestone_auth",
      startDate: iso(subDays(now, 1)),
      dueDate: iso(addDays(now, 2)),
      targetDate: iso(addDays(now, 2)),
      subscriberIds: ["user_declan", "user_maya", "user_idris"],
      createdAt: iso(subDays(now, 14)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_fix_navigation",
      key: "REC-69",
      teamId: "team_recipe_room",
      type: "issue",
      title: "Fix live navigation",
      descriptionDocId: "doc_item_routes",
      status: "in-progress",
      priority: "medium",
      assigneeId: "user_maya",
      creatorId: "user_declan",
      parentId: null,
      primaryProjectId: "project_web_refresh",
      linkedProjectIds: [],
      linkedDocumentIds: [],
      labelIds: ["label_frontend"],
      milestoneId: "milestone_beta",
      startDate: iso(subDays(now, 3)),
      dueDate: iso(addDays(now, 4)),
      targetDate: iso(addDays(now, 6)),
      subscriberIds: ["user_declan", "user_maya"],
      createdAt: iso(subDays(now, 13)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_auth_reliability",
      key: "REC-117",
      teamId: "team_recipe_room",
      type: "issue",
      title: "Auth reliability",
      descriptionDocId: "doc_item_auth",
      status: "backlog",
      priority: "urgent",
      assigneeId: "user_declan",
      creatorId: "user_idris",
      parentId: "item_review_rls",
      primaryProjectId: "project_auth_qa",
      linkedProjectIds: ["project_release_hub"],
      linkedDocumentIds: ["doc_release_playbook", "doc_qa_matrix"],
      labelIds: ["label_qa", "label_release"],
      milestoneId: "milestone_auth",
      startDate: iso(subDays(now, 1)),
      dueDate: iso(addDays(now, 1)),
      targetDate: iso(addDays(now, 4)),
      subscriberIds: ["user_declan", "user_idris", "user_theo"],
      createdAt: iso(subDays(now, 10)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_mobile_cards",
      key: "REC-67",
      teamId: "team_recipe_room",
      type: "story",
      title: "Mobile cards",
      descriptionDocId: "doc_item_mobile_cards",
      status: "backlog",
      priority: "medium",
      assigneeId: "user_sofia",
      creatorId: "user_declan",
      parentId: null,
      primaryProjectId: "project_mobile_app",
      linkedProjectIds: [],
      linkedDocumentIds: [],
      labelIds: ["label_mobile", "label_design"],
      milestoneId: null,
      startDate: iso(addDays(now, 3)),
      dueDate: iso(addDays(now, 8)),
      targetDate: iso(addDays(now, 10)),
      subscriberIds: ["user_declan", "user_sofia"],
      createdAt: iso(subDays(now, 9)),
      updatedAt: iso(subDays(now, 4)),
    },
    {
      id: "item_release_notes",
      key: "REC-64",
      teamId: "team_recipe_room",
      type: "story",
      title: "Release notes",
      descriptionDocId: "doc_item_release",
      status: "todo",
      priority: "low",
      assigneeId: "user_theo",
      creatorId: "user_declan",
      parentId: null,
      primaryProjectId: "project_release_hub",
      linkedProjectIds: ["project_web_refresh"],
      linkedDocumentIds: ["doc_release_playbook"],
      labelIds: ["label_release", "label_docs"],
      milestoneId: "milestone_launch",
      startDate: iso(addDays(now, 5)),
      dueDate: iso(addDays(now, 13)),
      targetDate: iso(addDays(now, 14)),
      subscriberIds: ["user_declan", "user_theo"],
      createdAt: iso(subDays(now, 11)),
      updatedAt: iso(subDays(now, 2)),
    },
    {
      id: "item_project_views",
      key: "DEV-23",
      teamId: "team_development",
      type: "feature",
      title: "Workspace document views",
      descriptionDocId: "doc_platform_principles",
      status: "in-progress",
      priority: "high",
      assigneeId: "user_maya",
      creatorId: "user_declan",
      parentId: null,
      primaryProjectId: "project_platform_docs",
      linkedProjectIds: [],
      linkedDocumentIds: ["doc_platform_principles"],
      labelIds: ["label_docs"],
      milestoneId: null,
      startDate: iso(subDays(now, 4)),
      dueDate: iso(addDays(now, 7)),
      targetDate: iso(addDays(now, 9)),
      subscriberIds: ["user_declan", "user_maya"],
      createdAt: iso(subDays(now, 22)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_comment_permissions",
      key: "DEV-19",
      teamId: "team_development",
      type: "story",
      title: "Comment permission guardrails",
      descriptionDocId: "doc_platform_principles",
      status: "backlog",
      priority: "medium",
      assigneeId: "user_declan",
      creatorId: "user_maya",
      parentId: "item_project_views",
      primaryProjectId: "project_platform_docs",
      linkedProjectIds: ["project_auth_qa"],
      linkedDocumentIds: ["doc_platform_principles", "doc_qa_matrix"],
      labelIds: ["label_docs", "label_qa"],
      milestoneId: null,
      startDate: iso(addDays(now, 4)),
      dueDate: iso(addDays(now, 11)),
      targetDate: iso(addDays(now, 12)),
      subscriberIds: ["user_declan", "user_maya", "user_idris"],
      createdAt: iso(subDays(now, 12)),
      updatedAt: iso(subDays(now, 3)),
    },
    {
      id: "item_electron_boot",
      key: "REC-144",
      teamId: "team_recipe_room",
      type: "story",
      title: "Wire Electron shell boot",
      descriptionDocId: "doc_shell_inventory",
      status: "todo",
      priority: "high",
      assigneeId: "user_declan",
      creatorId: "user_maya",
      parentId: null,
      primaryProjectId: "project_web_refresh",
      linkedProjectIds: ["project_release_hub"],
      linkedDocumentIds: ["doc_platform_principles"],
      labelIds: ["label_frontend", "label_release"],
      milestoneId: "milestone_beta",
      startDate: iso(now),
      dueDate: iso(addDays(now, 5)),
      targetDate: iso(addDays(now, 6)),
      subscriberIds: ["user_declan", "user_maya", "user_theo"],
      createdAt: iso(subDays(now, 1)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "item_doc_mentions",
      key: "REC-148",
      teamId: "team_recipe_room",
      type: "sub-task",
      title: "Docs mentions and notifications",
      descriptionDocId: "doc_release_playbook",
      status: "backlog",
      priority: "medium",
      assigneeId: "user_sofia",
      creatorId: "user_declan",
      parentId: "item_release_notes",
      primaryProjectId: "project_release_hub",
      linkedProjectIds: ["project_platform_docs"],
      linkedDocumentIds: ["doc_release_playbook"],
      labelIds: ["label_docs", "label_release"],
      milestoneId: "milestone_launch",
      startDate: iso(addDays(now, 8)),
      dueDate: iso(addDays(now, 15)),
      targetDate: iso(addDays(now, 17)),
      subscriberIds: ["user_declan", "user_sofia"],
      createdAt: iso(subDays(now, 2)),
      updatedAt: iso(subDays(now, 1)),
    },
  ]

  const documents = [
    ...descriptionDocs,
    ...teamDocs,
    ...workspaceDocs,
    ...privateDocs,
  ]

  const comments: Comment[] = [
    {
      id: "comment_rls_1",
      targetType: "workItem",
      targetId: "item_review_rls",
      parentCommentId: null,
      content:
        "We should audit viewer and guest role behavior here before we wire the real invite flow. @declan @idris",
      mentionUserIds: ["user_declan", "user_idris"],
      reactions: [],
      createdBy: "user_maya",
      createdAt: iso(subDays(now, 1)),
    },
    {
      id: "comment_doc_1",
      targetType: "document",
      targetId: "doc_release_playbook",
      parentCommentId: null,
      content:
        "Add a short section for the Electron wrapper startup checklist before the launch review.",
      mentionUserIds: [],
      reactions: [],
      createdBy: "user_theo",
      createdAt: iso(subDays(now, 2)),
    },
  ]

  const notifications: Notification[] = [
    {
      id: "notification_1",
      userId: "user_declan",
      type: "mention",
      entityType: "workItem",
      entityId: "item_review_rls",
      actorId: "user_maya",
      message: "Maya mentioned you in Review RLS",
      readAt: null,
      emailedAt: iso(subDays(now, 1)),
      createdAt: iso(subDays(now, 1)),
    },
    {
      id: "notification_2",
      userId: "user_declan",
      type: "assignment",
      entityType: "workItem",
      entityId: "item_auth_reliability",
      actorId: "user_idris",
      message: "Idris assigned you Auth reliability",
      readAt: null,
      emailedAt: iso(subDays(now, 1)),
      createdAt: iso(subDays(now, 1)),
    },
    {
      id: "notification_3",
      userId: "user_declan",
      type: "comment",
      entityType: "document",
      entityId: "doc_release_playbook",
      actorId: "user_theo",
      message: "Theo commented on Release Playbook",
      readAt: iso(subDays(now, 1)),
      emailedAt: null,
      createdAt: iso(subDays(now, 2)),
    },
    {
      id: "notification_4",
      userId: "user_declan",
      type: "status-change",
      entityType: "workItem",
      entityId: "item_fix_navigation",
      actorId: "user_maya",
      message: "Fix live navigation moved to In Progress",
      readAt: null,
      emailedAt: null,
      createdAt: iso(subDays(now, 1)),
    },
  ]

  const invites: Invite[] = [
    {
      id: "invite_1",
      workspaceId: workspace.id,
      teamId: "team_development",
      email: "newhire@example.com",
      role: "viewer",
      token: "invite_1_token",
      joinCode: "DEV42",
      invitedBy: "user_maya",
      expiresAt: iso(addDays(now, 7)),
      acceptedAt: null,
      declinedAt: null,
    },
  ]

  const projectUpdates: ProjectUpdate[] = [
    {
      id: "update_1",
      projectId: "project_web_refresh",
      content:
        "The shell layout is stable. Remaining work is mostly on the richer filters, saved views, and desktop affordances.",
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 2)),
    },
    {
      id: "update_2",
      projectId: "project_auth_qa",
      content:
        "Join codes now map cleanly to team-scoped viewer access in the mocked flow. Need final permission verification.",
      createdBy: "user_idris",
      createdAt: iso(subDays(now, 3)),
    },
    {
      id: "update_3",
      projectId: "project_release_hub",
      content:
        "Launch review materials are being consolidated into the Release Playbook doc.",
      createdBy: "user_theo",
      createdAt: iso(subDays(now, 4)),
    },
  ]

  const defaultFilters = {
    status: [],
    priority: [],
    assigneeIds: [],
    creatorIds: [],
    leadIds: [],
    health: [],
    milestoneIds: [],
    relationTypes: [],
    projectIds: [],
    itemTypes: [],
    labelIds: [],
    teamIds: [],
    showCompleted: true,
  }

  const views: ViewDefinition[] = [
    ...buildTeamWorkViews({
      teamId: "team_recipe_room",
      teamSlug: "recipe-room",
      createdAt: iso(subDays(now, 18)),
      updatedAt: iso(subDays(now, 1)),
      experience: "software-development",
    }),
    ...buildTeamWorkViews({
      teamId: "team_development",
      teamSlug: "development",
      createdAt: iso(subDays(now, 12)),
      updatedAt: iso(subDays(now, 2)),
      experience: "software-development",
    }),
    ...buildTeamWorkViews({
      teamId: "team_operations",
      teamSlug: "project-management",
      createdAt: iso(subDays(now, 10)),
      updatedAt: iso(subDays(now, 2)),
      experience: "project-management",
    }),
    {
      id: "view_workspace_projects",
      name: "Cross-team Projects",
      description: "Workspace-level project overview.",
      scopeType: "personal",
      scopeId: "user_declan",
      entityKind: "projects",
      layout: "list",
      filters: { ...defaultFilters },
      grouping: "team",
      subGrouping: null,
      ordering: "updatedAt",
      displayProps: ["priority", "project", "updated"],
      hiddenState: { groups: [], subgroups: [] },
      isShared: false,
      route: "/workspace/projects",
      createdAt: iso(subDays(now, 15)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "view_workspace_docs",
      name: "Team Docs",
      description: "Aggregate document space across joined teams.",
      scopeType: "personal",
      scopeId: "user_declan",
      entityKind: "docs",
      layout: "list",
      filters: { ...defaultFilters },
      grouping: "team",
      subGrouping: null,
      ordering: "updatedAt",
      displayProps: ["updated"],
      hiddenState: { groups: [], subgroups: [] },
      isShared: false,
      route: "/workspace/docs",
      createdAt: iso(subDays(now, 15)),
      updatedAt: iso(subDays(now, 1)),
    },
    {
      id: "view_personal_assigned",
      name: "My items",
      description: "Personal work inbox across joined teams.",
      scopeType: "personal",
      scopeId: "user_declan",
      entityKind: "items",
      layout: "list",
      filters: { ...defaultFilters, assigneeIds: ["user_declan"] },
      grouping: "status",
      subGrouping: null,
      ordering: "priority",
      displayProps: ["id", "project", "priority", "dueDate", "updated"],
      hiddenState: { groups: [], subgroups: [] },
      isShared: false,
      route: "/assigned",
      createdAt: iso(subDays(now, 5)),
      updatedAt: iso(subDays(now, 1)),
    },
  ]

  const conversations: Conversation[] = [
    {
      id: "conversation_workspace_direct_maya",
      kind: "chat",
      scopeType: "workspace",
      scopeId: workspace.id,
      variant: "direct",
      title: "Maya Chen",
      description: "Direct workspace chat",
      participantIds: ["user_declan", "user_maya"],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 6)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_workspace_group_launch",
      kind: "chat",
      scopeType: "workspace",
      scopeId: workspace.id,
      variant: "group",
      title: "Launch Room",
      description: "Cross-workspace coordination chat for launch planning.",
      participantIds: ["user_declan", "user_maya", "user_sofia", "user_idris"],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 4)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_workspace_channel",
      kind: "channel",
      scopeType: "workspace",
      scopeId: workspace.id,
      variant: "team",
      title: "Workspace channel",
      description:
        "Shared updates and threaded decisions for the whole workspace.",
      participantIds: [
        "user_declan",
        "user_maya",
        "user_sofia",
        "user_idris",
        "user_theo",
      ],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 8)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_team_recipe_chat",
      kind: "chat",
      scopeType: "team",
      scopeId: "team_recipe_room",
      variant: "team",
      title: "Recipe Room chat",
      description: "Fast-moving team discussion for delivery and release work.",
      participantIds: [
        "user_declan",
        "user_maya",
        "user_sofia",
        "user_idris",
        "user_theo",
      ],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 5)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_team_development_chat",
      kind: "chat",
      scopeType: "team",
      scopeId: "team_development",
      variant: "team",
      title: "Development chat",
      description: "Implementation coordination and architecture notes.",
      participantIds: ["user_declan", "user_maya", "user_sofia", "user_idris"],
      createdBy: "user_maya",
      createdAt: iso(subDays(now, 3)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_channel_release",
      kind: "channel",
      scopeType: "team",
      scopeId: "team_recipe_room",
      variant: "team",
      title: "Release Announcements",
      description:
        "Launch notes, blockers, and updates that need comments instead of chat replies.",
      participantIds: [
        "user_declan",
        "user_maya",
        "user_sofia",
        "user_idris",
        "user_theo",
      ],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 7)),
      updatedAt: iso(subDays(now, 0)),
      lastActivityAt: iso(subDays(now, 0)),
    },
    {
      id: "conversation_channel_design",
      kind: "channel",
      scopeType: "team",
      scopeId: "team_recipe_room",
      variant: "team",
      title: "Design Reviews",
      description:
        "Structured feedback threads for interaction and UI decisions.",
      participantIds: ["user_declan", "user_maya", "user_sofia", "user_idris"],
      createdBy: "user_sofia",
      createdAt: iso(subDays(now, 5)),
      updatedAt: iso(subDays(now, 1)),
      lastActivityAt: iso(subDays(now, 1)),
    },
  ]

  const chatMessages: ChatMessage[] = [
    {
      id: "chat_message_maya_1",
      conversationId: "conversation_workspace_direct_maya",
      kind: "text",
      content:
        "Can we keep the launch room for blockers and use this thread for implementation decisions?",
      callId: null,
      mentionUserIds: [],
      createdBy: "user_maya",
      createdAt: iso(subDays(now, 1)),
    },
    {
      id: "chat_message_maya_2",
      conversationId: "conversation_workspace_direct_maya",
      kind: "text",
      content:
        "Yes. I also want the team chat to carry a video placeholder for the 100MS handoff later.",
      callId: null,
      mentionUserIds: [],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 0)),
    },
    {
      id: "chat_message_launch_1",
      conversationId: "conversation_workspace_group_launch",
      kind: "text",
      content:
        "Posting final QA blockers here so launch comms and design stay aligned.",
      callId: null,
      mentionUserIds: [],
      createdBy: "user_idris",
      createdAt: iso(subDays(now, 0)),
    },
    {
      id: "chat_message_recipe_1",
      conversationId: "conversation_team_recipe_chat",
      kind: "text",
      content:
        "Channel work should feel slower and structured. Team chat should stay real-time.",
      callId: null,
      mentionUserIds: [],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 0)),
    },
    {
      id: "chat_message_dev_1",
      conversationId: "conversation_team_development_chat",
      kind: "text",
      content:
        "Schema work is first. Once snapshot sync lands, the UI will follow quickly.",
      callId: null,
      mentionUserIds: [],
      createdBy: "user_maya",
      createdAt: iso(subDays(now, 0)),
    },
  ]

  const calls: Call[] = []

  const channelPosts: ChannelPost[] = [
    {
      id: "channel_post_workspace_brief",
      conversationId: "conversation_workspace_channel",
      title: "Workspace Brief",
      content:
        "Use this channel for cross-team announcements, launch notes, and decisions that should stay visible after chat scrolls away.",
      reactions: [
        {
          emoji: "👍",
          userIds: ["user_maya"],
        },
      ],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 2)),
      updatedAt: iso(subDays(now, 0)),
    },
    {
      id: "channel_post_release_ready",
      conversationId: "conversation_channel_release",
      title: "Launch Readiness Snapshot",
      content:
        "Auth reliability is the last red flag. Docs and release notes are green, but QA still needs one more pass tomorrow morning.",
      reactions: [
        {
          emoji: "❤️",
          userIds: ["user_theo", "user_sofia"],
        },
      ],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 1)),
      updatedAt: iso(subDays(now, 0)),
    },
    {
      id: "channel_post_design_docs",
      conversationId: "conversation_channel_design",
      title: "Document Board Direction",
      content:
        "The docs index should feel calmer than the issues board. Keep the cards more editorial and reduce chrome around metadata.",
      reactions: [],
      createdBy: "user_sofia",
      createdAt: iso(subDays(now, 2)),
      updatedAt: iso(subDays(now, 1)),
    },
  ]

  const channelPostComments: ChannelPostComment[] = [
    {
      id: "channel_comment_workspace_1",
      postId: "channel_post_workspace_brief",
      content:
        "Perfect. I’ll use this for release-wide updates instead of burying them in chat.",
      mentionUserIds: [],
      createdBy: "user_maya",
      createdAt: iso(subDays(now, 0)),
    },
    {
      id: "channel_comment_release_1",
      postId: "channel_post_release_ready",
      content:
        "Agreed. I’ll handle the release note polish while QA finishes the final pass.",
      mentionUserIds: [],
      createdBy: "user_theo",
      createdAt: iso(subDays(now, 0)),
    },
    {
      id: "channel_comment_design_1",
      postId: "channel_post_design_docs",
      content:
        "That direction works. We should also show the document scope label more clearly.",
      mentionUserIds: [],
      createdBy: "user_declan",
      createdAt: iso(subDays(now, 1)),
    },
  ]

  return {
    currentUserId: "user_declan",
    currentWorkspaceId: workspace.id,
    workspaces: [workspace],
    teams,
    teamMemberships,
    users,
    labels,
    projects,
    milestones,
    workItems,
    documents,
    views,
    comments,
    attachments: [],
    notifications,
    invites,
    projectUpdates,
    conversations,
    calls,
    chatMessages,
    channelPosts,
    channelPostComments,
    ui: {
      activeTeamId: "team_recipe_room",
      rolePreview: null,
      activeInboxNotificationId: notifications[0]?.id ?? null,
      selectedViewByRoute: {
        "/team/recipe-room/work": "view_team_all",
        "/team/development/work": "view_dev_platform",
        "/assigned": "view_personal_assigned",
      },
    },
  }
}
