export const TIMELINE_HEADER_TOP_ROW_HEIGHT = 32
export const TIMELINE_HEADER_BOTTOM_ROW_HEIGHT = 32
export const TIMELINE_HEADER_TOP_ROW_HEIGHT_CLASS = "h-8"
export const TIMELINE_HEADER_BOTTOM_ROW_HEIGHT_CLASS = "h-8"
export const TIMELINE_GROUP_ROW_HEIGHT_CLASS = "h-10"
export const TIMELINE_ITEM_ROW_HEIGHT_CLASS = "h-9"
